blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/users/572173428086538270
    about: Reach out to me on Discord.
  - name: Tabroom.com
    url: https://tabrom.com
    about: Learn about Tabroom!