name: Release Project
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    name: Publish to Repository
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Publish to Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publish